export enum WebsocketType {
  USER_RECEPCAO = "USER_RECEPCAO",
  USER_ATENDIMENTO = "USER_ATENDIMENTO",
  USER_PREPARO = "USER_PREPARO",
  TICKET = "TICKET",
  PAINEL = "PAINEL",
  PRONTUARIO = "PRONTUARIO",
  SCRAPER = "SCRAPER",
}

export enum PreparationRequestTypes {
  CREATE = "CREATE",

  SUCCESS = "SUCCESS",
  ERROR = "ERROR",
  FINISHED = "FINISHED",
}
