export const ACAO_LABELS: Record<string, string> = {
  RECEPCAO_ATUALIZAR: "Recepção atualizada",
  EXAME_ATUALIZAR: "Exame atualizado",
  EXAME_REEMITIR: "Exame reemitido",
  PARECER_MEDICO: "Parecer médico",
  ANEXAR_RESULTADO: "Resultado anexado",
  UPLOAD_ANEXO: "Anexo enviado",
  REMOVER_ANEXO: "Anexo removido",
  EXCLUIR_ATENDIMENTO: "Atendimento excluído",
  VISUALIZAR_PRONTUARIO: "Prontuário visualizado",
  ASO_VISUALIZAR: "ASO visualizado",
  CONFIGURACAO_ALTERAR: "Configuração alterada",
  PSC_AUTENTICAR: "PSC autenticado",
  BIOMETRIA_CADASTRO_SUCESSO: "Biometria cadastrada",
  BIOMETRIA_CADASTRO_ERRO: "Erro no cadastro biométrico",
  BIOMETRIA_VALIDACAO_APROVADA: "Biometria aprovada",
  BIOMETRIA_VALIDACAO_REPROVADA: "Biometria reprovada",
  BIOMETRIA_VALIDACAO_ERRO: "Erro na validação biométrica",
  BIOMETRIA_CIENCIA_REGISTRADA: "Ciência biométrica registrada",
  BIOMETRIA_TERMO_GERADO: "Termo biométrico gerado",
  FACIAL_CIENCIA_REGISTRADA: "Ciência facial registrada",
  ATENDIMENTO_AUTH_FACIAL_FINALIZADA: "Autenticação facial finalizada",
  ATENDIMENTO_AUTH_CONTEXT_RESOLVED: "Contexto de autenticação resolvido",
  ATENDIMENTO_AUTH_VALIDACAO_REGISTRADA: "Validação de autenticação registrada",
  ATENDIMENTO_AUTH_IDENTIDADE_RESOLVIDA: "Identidade resolvida",
  ATENDIMENTO_AUTH_LGPD_ANONIMIZACAO_REALIZADA: "Anonimização LGPD realizada",
  ATENDIMENTO_AUTH_POLICY_SCHEDULING_AUSENTE: "Agendamento ausente (política)",
  ATENDIMENTO_AUTH_POLICY_UNIDADE_DIVERGENTE: "Unidade divergente (política)",
  ATENDIMENTO_AUTH_POLICY_IDENTIDADE_INSUFICIENTE: "Identidade insuficiente (política)",
  ATENDIMENTO_AUTH_POLICY_ACAO_INVALIDA: "Ação inválida (política)",
  CRIAR_EXAME: "Exame criado",
  EDITAR_EXAME: "Exame editado",
  EXCLUIR_EXAME: "Exame excluído",
  USUARIO_ATUALIZADO: "Usuário atualizado",
  USUARIO_SINCRONIZADO: "Usuário sincronizado",
  USUARIO_EXCLUIDO: "Usuário excluído",
  EXCLUIR_UNIDADE: "Unidade excluída",
};

export function getAcaoLabel(acao: string): string {
  return ACAO_LABELS[acao] ?? acao;
}
