export const AUDIT_ACTION_OPTIONS = [
  { label: "Recepção atualizada", value: "RECEPCAO_ATUALIZAR" },
  { label: "Exame atualizado", value: "EXAME_ATUALIZAR" },
  { label: "Exame reemitido", value: "EXAME_REEMITIR" },
  { label: "Parecer médico", value: "PARECER_MEDICO" },
  { label: "Resultado anexado", value: "ANEXAR_RESULTADO" },
  { label: "Anexo enviado", value: "UPLOAD_ANEXO" },
  { label: "Anexo removido", value: "REMOVER_ANEXO" },
  { label: "Atendimento excluído", value: "EXCLUIR_ATENDIMENTO" },
  { label: "Prontuário visualizado", value: "VISUALIZAR_PRONTUARIO" },
  { label: "ASO visualizado", value: "ASO_VISUALIZAR" },
  { label: "Documento visualizado", value: "VISUALIZAR_DOCUMENTO_PROXY" },
  { label: "Documento visualizado (fallback)", value: "VISUALIZAR_DOCUMENTO_PROXY_FALLBACK" },
  { label: "Configuração alterada", value: "CONFIGURACAO_ALTERAR" },
  { label: "PSC autenticado", value: "PSC_AUTENTICAR" },
  { label: "Biometria cadastrada", value: "BIOMETRIA_CADASTRO_SUCESSO" },
  { label: "Erro no cadastro biométrico", value: "BIOMETRIA_CADASTRO_ERRO" },
  { label: "Biometria aprovada", value: "BIOMETRIA_VALIDACAO_APROVADA" },
  { label: "Biometria reprovada", value: "BIOMETRIA_VALIDACAO_REPROVADA" },
  { label: "Erro na validação biométrica", value: "BIOMETRIA_VALIDACAO_ERRO" },
  { label: "Ciência biométrica registrada", value: "BIOMETRIA_CIENCIA_REGISTRADA" },
  { label: "Termo biométrico gerado", value: "BIOMETRIA_TERMO_GERADO" },
  { label: "Ciência facial registrada", value: "FACIAL_CIENCIA_REGISTRADA" },
  { label: "Autenticação facial finalizada", value: "ATENDIMENTO_AUTH_FACIAL_FINALIZADA" },
  { label: "Contexto de autenticação resolvido", value: "ATENDIMENTO_AUTH_CONTEXT_RESOLVED" },
  { label: "Validação de autenticação registrada", value: "ATENDIMENTO_AUTH_VALIDACAO_REGISTRADA" },
  { label: "Identidade resolvida", value: "ATENDIMENTO_AUTH_IDENTIDADE_RESOLVIDA" },
  { label: "Anonimização LGPD realizada", value: "ATENDIMENTO_AUTH_LGPD_ANONIMIZACAO_REALIZADA" },
  { label: "Agendamento ausente (política)", value: "ATENDIMENTO_AUTH_POLICY_SCHEDULING_AUSENTE" },
  { label: "Unidade divergente (política)", value: "ATENDIMENTO_AUTH_POLICY_UNIDADE_DIVERGENTE" },
  { label: "Identidade insuficiente (política)", value: "ATENDIMENTO_AUTH_POLICY_IDENTIDADE_INSUFICIENTE" },
  { label: "Ação inválida (política)", value: "ATENDIMENTO_AUTH_POLICY_ACAO_INVALIDA" },
  { label: "Exame criado", value: "CRIAR_EXAME" },
  { label: "Exame editado", value: "EDITAR_EXAME" },
  { label: "Exame excluído", value: "EXCLUIR_EXAME" },
  { label: "Usuário atualizado", value: "USUARIO_ATUALIZADO" },
  { label: "Usuário sincronizado", value: "USUARIO_SINCRONIZADO" },
  { label: "Usuário excluído", value: "USUARIO_EXCLUIDO" },
  { label: "Unidade excluída", value: "EXCLUIR_UNIDADE" },
  { label: "Configuração de risco criada", value: "CRIAR_RISCO_CONFIG" },
  { label: "Configuração de risco editada", value: "EDITAR_RISCO_CONFIG" },
  { label: "Configuração de risco excluída", value: "EXCLUIR_RISCO_CONFIG" },
  { label: "Prestador criado", value: "CRIAR_PRESTADOR" },
  { label: "Prestador editado", value: "EDITAR_PRESTADOR" },
  { label: "Prestador excluído", value: "EXCLUIR_PRESTADOR" },
  { label: "Grupo criado", value: "CRIAR_GRUPO" },
  { label: "Grupo editado", value: "EDITAR_GRUPO" },
  { label: "Grupo excluído", value: "EXCLUIR_GRUPO" },
  { label: "Consentimento aceito", value: "CONSENTIMENTO_ACEITO" },
  { label: "Consentimento rejeitado", value: "CONSENTIMENTO_REJEITADO" },
];
