export enum AsoStatus {
  NAO_GERADO = 'NAO_GERADO',
  GERADO = 'GERADO',
  KIT_CREDENCIADA = "KIT_CREDENCIADA",
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
  ENVIADO = 'ENVIADO',
}

export enum AtendimentoStatus {
  AGENDADO = "AGENDADO",
  EM_ATENDIMENTO = "ATENDIMENTO",
  AGUARDANDO_RESULTADOS = "AGUARDANDO_RESULTADOS",
  AGUARDANDO_AVALIACAO_MEDICA = "AGUARDANDO_AVALIACAO_MEDICA",
  FINALIZADO = "FINALIZADO",
}

export enum ExamStatus {
    PENDENTE = "PENDENTE",
    AGUARDANDO_RESULTADO = "AGUARDANDO_RESULTADO",
    FINALIZADO = "FINALIZADO"
}

export enum MongoOperationTypes {
  INSERT = "insert",
  REPLACE = "replace",
  UPDATE = "update",
  DELETE = "delete"
}